# Generated by Django 5.0.1 on 2024-01-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='analisis_cn',
            field=models.IntegerField(),
        ),
    ]
