# Generated by Django 5.0.1 on 2024-02-14 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cene',
            fields=[
                ('id_cene', models.CharField(max_length=15, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
    ]
