# Generated by Django 5.0.1 on 2024-01-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('fecha_asignacion', models.DateField()),
                ('monto_neto', models.IntegerField()),
                ('empresa', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('comuna', models.CharField(max_length=45)),
                ('tipo_obra', models.CharField(max_length=45)),
                ('estado_obra', models.CharField(max_length=45)),
                ('observaciones', models.TextField()),
                ('porc_avance', models.IntegerField()),
                ('monto_facturado', models.IntegerField()),
            ],
        ),
    ]
