# Generated by Django 5.0.1 on 2024-01-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obras',
            name='saldo_facturado',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='obras',
            name='porc_avance',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
