# Generated by Django 5.0.1 on 2024-02-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0003_obras_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obras',
            name='porc_avance',
            field=models.IntegerField(),
        ),
    ]
