# Generated by Django 5.0.1 on 2024-02-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0004_alter_obras_porc_avance'),
    ]

    operations = [
        migrations.AddField(
            model_name='obras',
            name='gantt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='obras',
            name='presupuesto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='obras',
            name='monto_facturado',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='obras',
            name='observaciones',
            field=models.TextField(null=True),
        ),
    ]
