export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const SIGNUP_SUCCES = 'SIGNUP_SUCCES'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'
export const LOGIN_SUCCES = 'LOGIN_SUCCES'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'