# Generated by Django 5.0.1 on 2024-02-29 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras', '0001_initial'),
        ('perfil_usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.IntegerField()),
                ('porcentaje', models.IntegerField(default=0)),
                ('id_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.obras')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='perfil_usuario.userprofile')),
            ],
        ),
    ]
